---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: e8997fbaa2fe285612a028cd4e1753ef545b1039
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/snandakumar87/emitter-service.git
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: emitter-service
    provider: fabric8
    version: 1.0.0.0
    group: fraud.demo
  name: emitter-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: emitter-service
    provider: fabric8
    group: fraud.demo
