spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 500Mi
            limits:
              cpu: "1.0"
              memory: 500Mi
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: PRODUCER_TOPIC
              value: incoming-transaction
            - name: SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: SERIALIZER_CLASS
              value: fraud.analysis.demo.transaction.fraud.analysis.Serde.TransactionSerializer
            - name: ACKS
              value: 1

